### ISSUE TITLE
Re-Designing Cards in ALSO v4

### ISSUE THREAD

**Issue by Shreyas-SAS** [sugarlabs/aslo-v4#75] opened 2022-04-15 07:46 UTC
Taking reference from discussion on issue #71 

### I propose to make the following changes.

1. Addition of brief description to all activities.
2. Resizing cards to equal sizes.
3. Creating a hover effect on cards when mouse is moved on it.

**Comment by Shreyas-SAS** [comment] 2022-04-15 07:48
@srevinsaju @quozl I request you to please take a look at the issue and assign me to work on it.

**Comment by quozl** [comment] 2022-04-15 07:50
We do not assign issues. We also don't create issues for things that we are going to fix ourselves. Issues are usually created for things we are not going to fix, or by people who don't have any plan to fix them. So an issue that you plan to fix is a bit unusual. I suggest opening a pull request instead.

**Comment by Shreyas-SAS** [comment] 2022-04-15 08:20
> We do not assign issues. We also don't create issues for things that we are going to fix ourselves. Issues are usually created for things we are not going to fix, or by people who don't have any plan to fix them. So an issue that you plan to fix is a bit unusual. I suggest opening a pull request instead.

(repeated suggestion from issue #74 comments)

oh ok. in sugarizer we usually created an issue to tell others what we are going to work on so that they could also suggest changes as well as counter the change, 

many times it has happened in sugarizer that whenever one creates an issue, some other person may express his view on the issue and both parties come to an agreement of not going forward with the issue, it is a great practice I feel that should also be included on other sugar repositories.

You can see an example here of why issue creation before working could be really useful:
[issue on sugarizer](https://github.com/llaske/sugarizer/issues/1028)

**Comment by quozl** [comment] 2022-04-15 10:32
Closing as duplicate of https://github.com/sugarlabs/aslo-v4/issues/71

**Closed by quozl** 2022-04-15 10:32 UTC
